image:
  file: .gitpod.Dockerfile
ports:
  - port: 3000
    onOpen: open-preview
    visibility: public
    name: Astro
tasks:
  - name: Astro
    init: |
      curl https://get.volta.sh | bash -s -- --skip-setup
      volta install node
      npm ci
      npm i -g astro prettier wrangler
    command: astro dev

vscode:
  extensions:
    - astro-build.astro-vscode
    - EditorConfig.EditorConfig
    - ms-azuretools.vscode-docker
    - esbenp.prettier-vscode
    - GitHub.vscode-pull-request-github
    - eamodio.gitlens

github:
  prebuilds:
    branches: true
    pullRequestsFromForks: true
    addBadge: true
    addCheck: prevent-merge-on-error
